### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by RRRoger** [LionYe/chart_tool#1]
![](https://ws2.sinaimg.cn/large/9150e4e5ly1ffivj9rsc3g205c03p7wb.gif)

**Comment by LionYe** [comment]
![](https://api.superbed.cn/pic/5c3836929dc6d66c52223bac)

**Comment by RRRoger** [comment]
![](https://api.superbed.cn/pic/5c3837729dc6d66c52223baf)

**Comment by RRRoger** [comment]
close吧
